#!/usr/bin/env python
#
# puffbird documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(1, os.path.abspath('..'))

import puffbird

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Puffbird'
copyright = "2020, Matthias Christenson"
author = "Matthias Christenson"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = puffbird.__version__
# The full version, including alpha/beta/rc tags.
release = puffbird.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
extensions = [
    'nbsphinx',
    'nbsphinx_link',
    'sphinx.ext.mathjax',
    'm2r',
    # 'recommonmark',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'numpydoc',
    'sphinx.ext.inheritance_diagram',
    'sphinx_automodapi.automodapi',
    'sphinx_automodapi.smart_resolver',
]

autosummary_generate = True
# autodoc_default_flags = ['members']
numpydoc_show_class_members = False
automodsumm_inherited_members = True

# source_parsers = {
#    '.md': 'recommonmark.parser.CommonMarkParser',
# }
# source_suffix = '.rst'
source_suffix = ['.rst', '.md']
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = 'nature'
html_theme = 'pydata_sphinx_theme'
html_theme_options = {
    "github_url": "https://github.com/gucky92/dreye"
}
html_context = {
    "github_user": "gucky92",
    "github_repo": "https://github.com/gucky92/dreye",
    "github_version": "master",
    "doc_path": "docs"
}
html_logo = '_static/logo.svg'

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Don't add .txt suffix to source files (available for Sphinx >= 1.5):
html_sourcelink_suffix = ''
# Work-around until https://github.com/sphinx-doc/sphinx/issues/4229 is solved:
highlight_language = 'python3'
html_scaled_image_link = False
nbsphinx_allow_errors = True
nbsphinx_execute = 'never'

# Napoleon settings
napoleon_numpy_docstring = True
master_doc = 'index'

# -- Options for HTMLHelp output ---------------------------------------

# # Output file base name for HTML help builder.
# htmlhelp_basename = 'puffbirddoc'


# -- Options for LaTeX output ------------------------------------------
#
# latex_elements = {
#     # The paper size ('letterpaper' or 'a4paper').
#     #
#     # 'papersize': 'letterpaper',
#
#     # The font size ('10pt', '11pt' or '12pt').
#     #
#     # 'pointsize': '10pt',
#
#     # Additional stuff for the LaTeX preamble.
#     #
#     # 'preamble': '',
#
#     # Latex figure (float) alignment
#     #
#     # 'figure_align': 'htbp',
# }
#
# # Grouping the document tree into LaTeX files. List of tuples
# # (source start file, target name, title, author, documentclass
# # [howto, manual, or own class]).
# latex_documents = [
#     (master_doc, 'puffbird.tex',
#      'Puffbird Documentation',
#      'gucky92', 'manual'),
# ]
#
#
# # -- Options for manual page output ------------------------------------
#
# # One entry per manual page. List of tuples
# # (source start file, name, description, authors, manual section).
# man_pages = [
#     (master_doc, 'puffbird',
#      'Puffbird Documentation',
#      [author], 1)
# ]
#
#
# # -- Options for Texinfo output ----------------------------------------
#
# # Grouping the document tree into Texinfo files. List of tuples
# # (source start file, target name, title, author,
# #  dir menu entry, description, category)
# texinfo_documents = [
#     (master_doc, 'puffbird',
#      'Puffbird Documentation',
#      author,
#      'puffbird',
#      'One line description of project.',
#      'Miscellaneous'),
# ]
